---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: tenants-git
  namespace: tenants
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchLabels:
      acm-app: tenants-git
