---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: local
  namespace: tenants
  labels:
    meta.helm.sh/release-name: tenants
spec:
  clusterSelector:
    matchLabels:
      local-cluster: "true"
